# Generated by Django 5.0.6 on 2024-06-15 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='app.product', verbose_name='Номер товара'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default=2, verbose_name='Количество'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='OrderDetail',
        ),
    ]
